### PR TITLE
fix pep8

### PR DESCRIPTION
**Pull request by chungg**

### CODE REVIEW

**Comment by jd** [comment]
Supposedly there's a pep8 job so?

**Comment by sileht** [comment]
That was already pep8 valid. pep8 doesn't care the number of indent it just want thing that should have the same level have it.

**Comment by chungg** [comment]
there is a pep8 job. maybe pep8 is not an accurate description. i'm just fixing whatever was failing. i just ignored the failures when i merged the s3rver branch[1][2]

[1] https://github.com/gnocchixyz/ci-tools/pull/2
[2] https://travis-ci.org/gnocchixyz/ci-tools/builds/240356958?utm_source=github_status&utm_medium=notification

**Comment by sileht** [comment]
Maybe I'm drunk, I have tested it and pep8 failed... I have also run "gnocchixyz-branches-config" on this repo, to ensure we need to CI to merge.

**Comment by jd** [comment]
Seems like Travis now sees those failure. Mergin!

**Pull request merged**
